# Generated by Django 4.2.7 on 2024-01-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fileserver", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClientModel",
            new_name="Client",
        ),
        migrations.RenameModel(
            old_name="FileModel",
            new_name="File",
        ),
    ]
