# Generated by Django 4.2.7 on 2024-01-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fileserver", "0002_rename_clientmodel_client_rename_filemodel_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Client",
        ),
    ]
