# Generated by Django 4.2.7 on 2024-01-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileserver", "0004_alter_file_options_rename_file_location_file_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="username",
            field=models.CharField(default="", max_length=225),
        ),
    ]
